http:  
  middlewares:
    force-https:
      redirectScheme:
        scheme: https
        permanent: true
    hsts-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
